-- Databricks notebook source
--CREATE STREAMING TABLE
CREATE OR REFRESH STREAMING TABLE st_orders
AS
SELECT * FROM STREAM(samples.tpch.orders)

-- COMMAND ----------

--CREATE OR REPLACE MATERIALIZE VIEW
CREATE OR REPLACE MATERIALIZED VIEW agg_orders
AS
SELECT O_ORDERSTATUS,
COUNT(O_ORDERKEY) AS CNT_ORDERS
FROM LIVE.ST_ORDERS
GROUP BY O_ORDERSTATUS
